### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlretrieve'

### ISSUE THREAD

**Issue by MSpaceDev** [Pokechu22/Burger#10]
![image](https://user-images.githubusercontent.com/21283721/43996488-ec49e778-9dc3-11e8-9bc6-129fc3091854.png)

When running `python3 munch.py --download` I get the error seen above. I'm using `Python3.7.0`.

**Comment by MSpaceDev** [comment]
Of course. Didn't realise the `--download` wasn't being worked on. I'll download it and give it a test

**Comment by Pokechu22** [comment]
I've reimplemented the download function (among other things, it now lets you specify a list of versions to download; I think back when it was first implemented there was only a single minecraft.jar URL and the version for it wasn't known ahead of time).  This should be fixed on the 1.14-dev branch now; let me know if you still have trouble.
