### ISSUE TITLE
Can we extract item multiplier and book multiplier for anvils?

### ISSUE THREAD

**Issue by u9g** [Pokechu22/Burger#21]
the two columns on the right of this table: https://minecraft.gamepedia.com/Anvil_mechanics#Costs_for_combining_enchantments , I don't know of a single other source for this data, so being able to have it dumped in a readable format would be great. For `minecraft-data`, as of now we just manually get it from the table, but it would be great to automate it.

**Comment by Pokechu22** [comment]
A quick look at the relevant code indicates that the multiplier for items depends on the depends on the enchantment's "rarity", which is one of COMMON, UNCOMMON, RARE, and VERY_RARE (these are used both for the weights of getting the enchantment (10, 5, 2, and 1 respectively), and the multipliers you're interested in (1, 2, 4, 8)).  The multiplier for books is simply `min(1, orig_multipler/2)` (i.e. (1, 1, 2, 4)).

This data could definitely be extracted, though it'd require enchantments to be extracted as well (see #16, though I'm not sure if the approach there finds the right class to determine enchantment rarities).

**Comment by u9g** [comment]
> A quick look at the relevant code indicates that the multiplier for items depends on the depends on the enchantment's "rarity", which is one of COMMON, UNCOMMON, RARE, and VERY_RARE (these are used both for the weights of getting the enchantment (10, 5, 2, and 1 respectively), and the multipliers you're interested in (1, 2, 4, 8)).  The multiplier for books is simply `min(1, orig_multipler/2)` (i.e. (1, 1, 2, 4)).
> 
> 
> 
> This data could definitely be extracted, though it'd require enchantments to be extracted as well (see #16, though I'm not sure if the approach there finds the right class to determine enchantment rarities).

Thanks for the algorithm
