### ISSUE TITLE
Hamburglar seems not to be picking up on some changes

### ISSUE THREAD

**Issue by Pokechu22** [Pokechu22/Burger#7]
After seeing [this](http://wiki.vg/index.php?title=Pre-release_protocol&diff=13910&oldid=13908) by @Cybermaxke, something is clearly broken: Hamburger's diff did not show that change, or [any packet changes](http://pokechu22.github.io/Burger/diff_18w19b_18w20a.html#packets).  But weirdly, burger itself did see different packets: [18w19b](http://pokechu22.github.io/Burger/18w19b.html#packets:0x46), [18w20a](http://pokechu22.github.io/Burger/18w20a.html#packets:0x46).

So for the moment, don't trust the packet diffs as exhaustive.  I'm not sure why this is happening.

**Comment by Cybermaxke** [comment]
I didn't make the changes, @Gerrygames did ;)

**Comment by Pokechu22** [comment]
Oops.  Don't know why I thought you did.

In any case, fixed (pokechu22/Hamburglar@169248e).  For some reason, I was ignoring changes inside `if` and `switch` statements -- I think the goal was to ignore the _condition_ which often has obfuscated names, but that seems to not have been what actually happened).  Here's what was missed for 1.13:

* `diff_17w46a_17w47a`: missed `PLAY_CLIENTBOUND_43` "Scoreboard Objective", which lost a field.
* `diff_17w47b_17w48a`: missed `PLAY_SERVERBOUND_17` "Recipe book data", changed VarInt to identifier.  **Missed on the wiki**
* `diff_17w48a_17w49a`: missed `PLAY_CLIENTBOUND_43` "Scoreboard Objective", re-adding the update display name option(?)
* `diff_18w05a_18w06a`: missed `PLAY_SERVERBOUND_17` "Recipe Book Data" (serverbound), adding the furnace fields
* `diff_18w19b_18w20a`: missed `PLAY_CLIENTBOUND_46` "Teams", re-adding the prefix and suffix

I'll be regenerating all the data for this soon; currently it hasn't been regenerated.
