### ISSUE TITLE
"jawa.transforms" is not a package

### ISSUE THREAD

**Issue by MSpaceDev** [Pokechu22/Burger#9]
So, I've just cloned the `1.13-fixes` branch into my `Repos` folder. I've installed the `Jawa` package.

I get this error when I run:
`python3 munch.py --list` (Or any other munch command)
![image](https://user-images.githubusercontent.com/21283721/43845987-8d359c98-9b2d-11e8-976c-6e4bbfec7055.png)

When I uninstall the Jawa package, then it simply says `missing Jawa package`. But when I install the jawa package, then it brings up this error.

Also, my Python `Path` is setup properly before you ask

Installs commands I've run:
`git clone https://path_to_git/Burger.git --branch 1.13-fixes`
`python3 setup.py install`
`python3 -m pip install jawa`
`python3 munch.py --list`

**Comment by Pokechu22** [comment]
Oops, apparently I had a dirty local install where java.transforms was both a module and a package; fixed.
